default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DEVELOPMENT_DB_HOST") %>
  database: <%= ENV.fetch("DEVELOPMENT_DB_NAME") %>
  port: "<%= ENV['DEVELOPMENT_DB_PORT'] %>"
  username: <%= ENV.fetch("DEVELOPMENT_DB_USERNAME") %>
  password: <%= ENV.fetch("DEVELOPMENT_DB_PASSWORD") %>
 
test:
  <<: *default
  host: <%= ENV.fetch("TEST_DB_HOST") %>
  port: "<%= ENV['TEST_DB_PORT'] %>"
  database: <%= ENV.fetch("TEST_DB_NAME") %>
  username: <%= ENV.fetch("TEST_DB_USERNAME") %>
  password: <%= ENV.fetch("TEST_DB_PASSWORD") %>
